### ISSUE TITLE
project not working

### ISSUE THREAD

**Issue by UweW** [dceejay/nodered.snap#12]
Hi,
enabling the project feature in settings.js seems not to work.
The projects features and menue options are not available after a node-red restart.

    editorTheme: {
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: true
        }
    },

**Comment by dceejay** [comment]
this is probably due to git not being available within the strict environment.

**Comment by tonyarnold99** [comment]
I'm also seeing this issue and there is an entry in syslog saying projects disabled as git is not available. I've also tried installing node-red with classic confinement but this is not allowed either.

Is there a work around or a planned fix for this?

**Comment by dceejay** [comment]
Do you have git installed ?

**Comment by tonyarnold99** [comment]
I do have git installed, but as you surmised I think it is not available from within the snap.

**Comment by dceejay** [comment]
in classic mode you are supposed to be able to see system resources so I would think git should then be available...

**Comment by tonyarnold99** [comment]
Indeed but I've not found a way to install the snap in classic mode.

**Comment by dceejay** [comment]
does the `--classic` flag not work ?

**Comment by tonyarnold99** [comment]
Sorry for delay. Using the `--classic` flag gives the following:

```
ubuntu@open-kinkajou:~$ sudo snap install node-red --classic
Warning: flag --classic ignored for strictly confined snap node-red

node-red 1.0.3 from Node-RED-Team (noderedteam✓) installed
```
This is on Ubuntu 19.04

Tony.

**Comment by dceejay** [comment]
Ah you're right - they changed that behaviour a while back.. :-(
