### ISSUE TITLE
core18 support

### ISSUE THREAD

**Issue by rschwarz-sotec** [dceejay/nodered.snap#13]
Is an update to core18 planned?

**Comment by Sotec-IoT** [comment]
I would like to see this too 👍

**Comment by wer-is-paul** [comment]
Me too

**Comment by lesmuc** [comment]
Me too!

**Comment by olegkorol** [comment]
This would be great indeed!

**Comment by suhail-khan** [comment]
Waiting for this!

**Comment by dceejay** [comment]
Currently the online snap builder is failing to build with core18. so I have asked Canonical to comment.

**Comment by dceejay** [comment]
Thanks to the Canonical Snap guys for helping to fix this with a PR - https://github.com/dceejay/nodered.snap/pull/15/commits/e2479b984d0d4d2999fc5ac7d88bb3fee624ae22
I can safely say I couldn't have worked that out...

**Comment by dceejay** [comment]
@rschwarz-sotec 
Node-RED 1.0 beta now in the beta snap channel (based on core18)
1.0 coming soon
