### ISSUE TITLE
Auto-refresh from 590 to 600 caused a failure

### ISSUE THREAD

**Issue by adamjennison** [dceejay/nodered.snap#18]
My snap auto-refreshed from 590 to 600 at 2:31pm UTC - 01/07/20
It then failed to run with the following error in the log, I have reverted to 590 using snap revert node-red but the auto-refresh will push the 600 regardless :

Jul 01 15:04:14 NODE_RED_SERVER systemd[1]: Started Service for snap application node-red.node-red.
Jul 01 15:04:14 NODE_RED_SERVER node-red.node-red[4052]: NOW STARTING NODE-RED : /snap/node-red/600/bin/node-red -u /<NODE-RED_USER>/snap/node-red/600 on port 1880
Jul 01 15:04:14 NODE_RED_SERVER node-red.node-red[4076]: 1 Jul 15:04:14 - [info]
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: Welcome to Node-RED
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: ===================
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:16 - [info] Node-RED version: v1.1.0
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:16 - [info] Node.js  version: v10.21.0
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:16 - [info] Linux 5.4.0-37-generic x64 LE
Jul 01 15:04:16 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:16 - [info] Loading palette nodes
Jul 01 15:04:17 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:17 - [red] Uncaught Exception:
Jul 01 15:04:17 NODE_RED_SERVER node-red.node-red[4122]: 1 Jul 15:04:17 - TypeError: Cannot read property 'forEach' of undefined
Jul 01 15:04:17 NODE_RED_SERVER node-red.node-red[4122]:     at /snap/node-red/600/lib/node_modules/@node-red/registry/lib/library.js:31:19
Jul 01 15:04:17 NODE_RED_SERVER node-red.node-red[4122]:     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Jul 01 15:04:17 NODE_RED_SERVER systemd[1]: snap.node-red.node-red.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 15:04:17 NODE_RED_SERVER systemd[1]: snap.node-red.node-red.service: Failed with result 'exit-code'.
Jul 01 15:04:18 NODE_RED_SERVER systemd[1]: snap.node-red.node-red.service: Scheduled restart job, restart counter is at 5.
Jul 01 15:04:18 NODE_RED_SERVER systemd[1]: Stopped Service for snap application node-red.node-red.
Jul 01 15:04:18 NODE_RED_SERVER systemd[1]: snap.node-red.node-red.service: Start request repeated too quickly.
Jul 01 15:04:18 NODE_RED_SERVER systemd[1]: snap.node-red.node-red.service: Failed with result 'exit-code'.
Jul 01 15:04:18 NODE_RED_SERVER systemd[1]: Failed to start Service for snap application node-red.node-red.

**Comment by adamjennison** [comment]
I forgot to add -this is running on a VM ubuntu 20.04 lts server 4cpus with 4 gig of ram

**Comment by dceejay** [comment]
thanks - ok - have reverted stable to 595, 
left 600 on edge for now

**Comment by dceejay** [comment]
latest version require the latest version of snapd - you may need to install this from the edge channel
