### ISSUE TITLE
snap should store configuration in /var/snap/node-red

### ISSUE THREAD

**Issue by ThyMYthOS** [dceejay/nodered.snap#21]
For snaps with services it is advised to store data in $SNAP_DATA

> Directory for system data of a snap.
> 
> This directory is owned and writable by root and is meant to be used by background applications (daemons, services). Unlike SNAP_COMMON this directory is backed up and restored across snap refresh and snap revert operations.

**Comment by dceejay** [comment]
Not sure where we are using SNAP_COMMON - we store user data in $SNAP_USER_DATA

**Comment by ThyMYthOS** [comment]
SNAP_COMMON is not used, it's just mentioned in the documentation.
The issue is SNAP_DATA vs SNAP_USER_DATA. For a normal user it's the same, but for root SNAP_DATA is in /var/snap.
Linux service typically don't store their data in /root

**Comment by dceejay** [comment]
Where do we mention SNAP_COMMON in the docs ? can you provide a link ?
When a user runs the snap do they do so as root or as their user ?
so we should use SNAP_DATA ?

**Comment by dceejay** [comment]
Pushed a change to the edge channel - note you will also need latest snapd (probably also from edge)
please try it and report back. thanks

**Comment by ThyMYthOS** [comment]
I did get this error message after restart:
```
Die Berechtigungen konnten nicht entschlüsselt werden.

Die Datei mit den Flow-Berechtigungen ist verschlüsselt, aber der Schlüssel des Projekts fehlt oder ist ungültig.

Die Datei mit den Flow-Berechtigungen wird bei der nächsten Übernahme (deploy) zurückgesetzt. Alle vorhandenen Flow-Berechtigungen werden gelöscht.
```

**Comment by dceejay** [comment]
yes - I can't do anything about that :-)
